### ISSUE TITLE
Could you please publish this repo in https://github.com/linkedin-faq, thanks

### ISSUE THREAD

**Issue by Ebazhanov** [Sharpness-B/linked-practice#1]
Hello, Bendik! 

Thanks for accepting my invitation to become member at https://github.com/linkedin-faq
the reason why I was inviting you is to ask publish your repo https://github.com/Sharpness-B/linked-practice there
to make it more visible for global network.

So I would be happy if you will do it, thank you in advance!

**Comment by Sharpness-B** [comment]
Super cool to hear from you! Really!

I have done a series of improvements to the ropo already in the
organisation. Will wrap them up and push in series soon!

Thanks for the invitation! This is fun:)

I need to run now, but will update you:)

Best regards,
Bendik Skarpnes

man. 10. jan. 2022, 22:16 skrev Zhenja ***@***.***>:

**Comment by Ebazhanov** [comment]
Takk skal du ha 👍
